vim.pack.add({ "https://github.com/neovim/nvim-lspconfig", "https://github.com/WieeRd/auto-lsp.nvim" })
-- vim.lsp.enable("lua_ls")
-- vim.lsp.enable("nim_langserver")
vim.lsp.enable("ols")
-- require("auto-lsp").setup()
